#
# (C) Copyright 2009 bodhi <mibodhi@gmail.com>
# 
# Based on
# Marvell Semiconductor <www.marvell.com>
# Written-by: Prafulla Wadaskar <prafulla@marvell.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= pogo_v4.o
