#
# (C) Copyright 2014 bodhi <mibodhi@gmail.com>
#
# Based on
# (C) Copyright 2009
# Marvell Semiconductor <www.marvell.com>
# Written-by: Prafulla Wadaskar <prafulla@marvell.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= netgear_ms2110.o

