#
# Copyright (C) 2021 ingmar_k <ingmar_klein@web.de>
# Based on
# (C) Copyright 2015 bodhi <mibodhi@gmail.com>
#
# Based on
# (C) Copyright 2009
# Marvell Semiconductor <www.marvell.com>
# Written-by: Prafulla Wadaskar <prafulla@marvell.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= readynas_duo_v2.o

